#!/usr/bin/env bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset s off
xset -dpms
xsetroot -cursor_name left_ptr &
unclutter --timeout 2 --jitter 2 --fork &
xrdb -load ~/.config/X11/xresources &
xmodmap ~/.config/X11/xmodmap &

export CACA_DRIVER=ncurses

exec bspwm
