#!/usr/bin/env bash

### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
nitrogen --restore &
xsct 6500 &
fcitx -d &

### MONITORS ###
bspc monitor -d 1 2 3 8 9 0 - =

### BSPWM configuration ###
bspc config border_width 3
bspc config window_gap 7
bspc config top_padding 35
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM COLORING ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#bc3a36"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# focus options
bspc config focus_by_distance true
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false

### BSPWM RULES ###
bspc rule -a Slack desktop=^1
bspc rule -a firefox desktop=^2
bspc rule -a firefoxdeveloperedition desktop=^3
bspc rule -a Gnome-music desktop=^6
bspc rule -a gammy desktop=^7
bspc rule -a Pavucontrol state=floating
bspc rule -a 'firefoxdeveloperedition:Devtools' state=floating
bspc rule -a 'firefox:Tookit:Picture-in-Picture' focus=off
bspc rule -a 'firefox:Toolkit' state=floating
bspc rule -a 'Alacritty:qalc' state=floating
bspc rule -a 'Alacritty:video' state=pseudo_tiled
bspc rule -a 'Nitrogen' state=floating
bspc rule -a 'Org.gnome.Nautilus' state=floating
bspc rule -a 'zoom' state=floating
bspc rule -a 'steam_app_10' state=pseudo_tiled rectangle=1226x919

# adjusts cursor on root screen
xsetroot -cursor_name left_ptr &
