#!/usr/bin/env bash

### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
fcitx5 -rd &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
$HOME/bash-scripts/utils/set-random-wallpaper.sh &
gammy &

mouse_id_list="$(xinput | grep "$MOUSE"'.*pointer.*' | sed 's/.*id=\([0-9]\+\)[[:space:]].*/\1/')"
mouse_id_list=$(echo $mouse_id_list)
for mouse_id in $mouse_id_list; do xinput set-prop "$mouse_id" 307 0; done

#xinput list-props 'Wireless Controller Touchpad' | rg '.*Tapping Enabled \((\d+)\).*' -r '$1'
xinput set-prop 'Wireless Controller Touchpad' 307 0.5
xinput set-prop 'Wireless Controller Touchpad' 568 1
xinput set-prop 'Wireless Controller Touchpad' 296 1

xinput set-prop 'Sony Interactive Entertainment Wireless Controller Touchpad' 307 0.5
xinput set-prop 'Sony Interactive Entertainment Wireless Controller Touchpad' 568 1
xinput set-prop 'Sony Interactive Entertainment Wireless Controller Touchpad' 296 1

xrandr --newmode $MODE_P_CVT
xrandr --addmode $MONITOR_P \""$MODE_P_NAME"\"
xrandr --output "$MONITOR_P" --mode \""$MODE_P_NAME"\"

### MONITORS ###
bspc monitor -d 2 3 4 7 8 9 0 -

### BSPWM configuration ###
bspc config border_width 3
bspc config window_gap 3
bspc config top_padding 38
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM COLORING ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#bc3a36"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# focus options
bspc config focus_by_distance true
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false

### BSPWM RULES ###
bspc rule -a Slack desktop=^1
bspc rule -a gammy desktop=^7
bspc rule -a Pavucontrol state=floating
bspc rule -a 'LibreWolf:Devtools' state=floating
bspc rule -a 'LibreWolf:Toolkit:Picture-in-Picture' state=floating sticky=on focus=off
bspc rule -a 'Alacritty:qalc' state=floating
bspc rule -a 'mpv' state=fullscreen
bspc rule -a 'Cypress' state=floating
bspc rule -a 'Alacritty:video' state=pseudo_tiled
bspc rule -a 'Nitrogen' state=floating
bspc rule -a 'Thunar' state=floating
bspc rule -a 'zoom' state=floating
bspc rule -a 'Chromium' state=floating
bspc rule -a 'steam_app_10' state=pseudo_tiled rectangle=1913x1038+7+42
bspc rule -a 'alacritty -h' state=floating

# adjusts cursor on root screen
xsetroot -cursor_name left_ptr &
