#! /bin/sh

### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
gammy &
fcitx -d &

### MONITORS ###
bspc monitor -d 1 2 3 8 9 0

### BSPWM configuration ###
bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 20
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle false
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM COLORING ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# focus options
bspc config focus_follows_pointer false
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false
bspc config focus_by_distance true
bspc config history_aware_focus false

### BSPWM RULES ###
bspc rule -a gammy desktop=^6
# bspc rule -a 'zoom:zoom' state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a 'firefoxdeveloperedition:Devtools' state=floating
bspc rule -a 'firefox:Toolkit' state=floating
bspc rule -a 'Alacritty:qalc' state=floating

# adjusts cursor on root screen
xsetroot -cursor_name left_ptr &

# polybar hidden when fullscreen for vlc, youtube, mpv, etc.
xdo below -t $(xdo id -n root) $(xdo id -a eDP1)

